import os
from dotenv import load_dotenv

# Charge les variables d'environnement à partir du fichier .env
load_dotenv()

# Récupère la clé API depuis l'environnement
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")


# On déplace le gros dictionnaire de traductions ici
# =======================================================================
# SECTION 2.5 : DICTIONNAIRE DE TRADUCTIONS (VERSION FINALE COMPLÈTE)
# =======================================================================
TITLES = {
    'fr': {
        "FICHE_DE_LECON": "FICHE DE LEÇON APC", 
        "OBJECTIFS": "OBJECTIFS PÉDAGOGIQUES",
        "SITUATION_PROBLEME": "SITUATION PROBLÈME", 
        "DEROULEMENT": "DÉROULEMENT DE LA LEÇON",
        "INTRODUCTION": "Introduction (5 min)", 
        "ACTIVITE_1": "Activité 1: Découverte (10 min)",
        "ACTIVITE_2": "Activité 2: Conceptualisation et TRACE ÉCRITE (20 min)",
        "TRACE_ECRITE": "Trace Écrite", 
        "ACTIVITE_3": "Activité 3: Application (10 min)",
        "DEVOIRS": "DEVOIRS", 
        "JEU_BILINGUE": "JEU BILINGUE / BILINGUAL GAME",
        "HEADER_MATIERE": "Matière", 
        "HEADER_CLASSE": "Classe", 
        "HEADER_DUREE": "Durée",
        "HEADER_LECON": "Leçon du jour", 
        "PDF_TITLE": "Fiche de Leçon", 
        "PDF_AUTHOR": "Assistant Pédagogique TCHATCHI AI",
        "INT_TITRE_PRINCIPAL": "ACTIVITÉ D'INTÉGRATION", 
        "INT_COMPETENCES": "Compétences visées",
        "INT_SITUATION": "SITUATION D'INTÉGRATION (LE PROBLÈME)", 
        "INT_GUIDE": "GUIDE DE RÉSOLUTION POUR L'ENSEIGNANT",
        "INT_SOLUTION": "PROPOSITION DE SOLUTION DÉTAILLÉE",
        "INT_ETAPE_1": "Étape 1: Analyse du problème (10 min)", 
        "INT_ETAPE_2": "Étape 2: Mobilisation des acquis (15 min)",
        "INT_ETAPE_3": "Étape 3: Résolution en groupe (15 min)", 
        "INT_ETAPE_4": "Étape 4: Synthèse et Correction (10 min)",
        "EVAL_PARTIE_1": "PARTIE I : ÉVALUATION DES RESSOURCES", 
        "EVAL_SAVOIRS": "A. SAVOIRS",
        "EVAL_SAVOIR_FAIRE": "B. SAVOIR-FAIRE", 
        "EVAL_PARTIE_2": "PARTIE II : ÉVALUATION DE LA COMPÉTENCE",
        "EVAL_SITUATION_PROBLEME": "Situation Problème", 
        "EVAL_PRESENTATION": "PRÉSENTATION",
        "EVAL_QCM_TITRE": "SECTION A : QUESTIONS À CHOIX MULTIPLES", 
        "EVAL_STRUCTURED_TITRE": "SECTION B : QUESTIONS STRUCTURÉES",
        "EVAL_PDF_TITLE": "Évaluation Séquentielle",
        "EVAL_PDF_AUTHOR": "TCHATCHI AI - Évaluation",
        "EVAL_CORRIGE_TITRE": "CORRIGÉ DÉTAILLÉ",
        "INT_PDF_TITLE": "Activité d'Intégration",
        "INT_PDF_AUTHOR": "TCHATCHI AI - Activité Pédagogique"
    },
    'en': {
        "FICHE_DE_LECON": "CBA LESSON PLAN", 
        "OBJECTIFS": "LEARNING OBJECTIVES",
        "SITUATION_PROBLEME": "PROBLEM SITUATION", 
        "DEROULEMENT": "LESSON PLAN",
        "INTRODUCTION": "Introduction (5 min)", 
        "ACTIVITE_1": "Activity 1: Discovery (10 min)",
        "ACTIVITE_2": "Activity 2: Conceptualization and WRITTEN RECORD (20 min)",
        "TRACE_ECRITE": "Written Record", 
        "ACTIVITE_3": "Activity 3: Application (10 min)",
        "DEVOIRS": "HOMEWORK", 
        "JEU_BILINGUE": "BILINGUAL GAME / JEU BILINGUE",
        "HEADER_MATIERE": "Subject", 
        "HEADER_CLASSE": "Class", 
        "HEADER_DUREE": "Duration",
        "HEADER_LECON": "Lesson of the Day", 
        "PDF_TITLE": "Lesson Plan", 
        "PDF_AUTHOR": "TCHATCHI AI Pedagogical Assistant",
        "INT_TITRE_PRINCIPAL": "INTEGRATION ACTIVITY", 
        "INT_COMPETENCES": "Targeted Skills",
        "INT_SITUATION": "INTEGRATION SITUATION (THE PROBLEM)", 
        "INT_GUIDE": "RESOLUTION GUIDE FOR THE TEACHER",
        "INT_SOLUTION": "DETAILED PROPOSED SOLUTION",
        "INT_ETAPE_1": "Step 1: Problem Analysis (10 min)", 
        "INT_ETAPE_2": "Step 2: Mobilization of Knowledge (15 min)",
        "INT_ETAPE_3": "Step 3: Group Resolution (15 min)", 
        "INT_ETAPE_4": "Step 4: Synthesis and Correction (10 min)",
        "EVAL_PARTIE_1": "PART I: ASSESSMENT OF RESOURCES", 
        "EVAL_SAVOIRS": "A. KNOWLEDGE",
        "EVAL_SAVOIR_FAIRE": "B. KNOW-HOW", 
        "EVAL_PARTIE_2": "PART II: ASSESSMENT OF COMPETENCE",
        "EVAL_SITUATION_PROBLEME": "Problem Situation", 
        "EVAL_PRESENTATION": "PRESENTATION",
        "EVAL_QCM_TITRE": "SECTION A: MULTIPLE CHOICE QUESTIONS", 
        "EVAL_STRUCTURED_TITRE": "SECTION B: STRUCTURED QUESTIONS",
        "EVAL_PDF_TITLE": "Sequential Assessment",
        "EVAL_PDF_AUTHOR": "TCHATCHI AI - Assessment",
        "EVAL_CORRIGE_TITRE": "DETAILED ANSWER KEY",
        "INT_PDF_TITLE": "Integration Activity",
        "INT_PDF_AUTHOR": "TCHATCHI AI - Pedagogical Activity"
    },
    'de': {
        "FICHE_DE_LECON": "LEKTIONSPLAN (CBA)", 
        "OBJECTIFS": "LERNZIELE", 
        "SITUATION_PROBLEME": "PROBLEMSITUATION",
        "DEROULEMENT": "LEKTIONSVERLAUF", 
        "INTRODUCTION": "Einführung (5 min)", 
        "ACTIVITE_1": "Aktivität 1: Entdeckung (10 min)",
        "ACTIVITE_2": "Aktivität 2: Konzeptualisierung und SCHRIFTLICHER EINTRAG (20 min)", 
        "TRACE_ECRITE": "Schriftlicher Eintrag",
        "ACTIVITE_3": "Aktivität 3: Anwendung (10 min)", 
        "DEVOIRS": "HAUSAUFGABEN", 
        "JEU_BILINGUE": "ZWEISPRACHIGES SPIEL",
        "HEADER_MATIERE": "Fach", 
        "HEADER_CLASSE": "Klasse", 
        "HEADER_DUREE": "Dauer", 
        "HEADER_LECON": "Heutige Lektion",
        "PDF_TITLE": "Lektionsplan", 
        "PDF_AUTHOR": "Pädagogischer Assistent TCHATCHI AI",
        "INT_TITRE_PRINCIPAL": "INTEGRATIONSAKTIVITÄT", 
        "INT_COMPETENCES": "Angestrebte Kompetenzen",
        "INT_SITUATION": "INTEGRATIONSSITUATION (DAS PROBLEM)", 
        "INT_GUIDE": "LÖSUNGSLEITFADEN FÜR DEN LEHRER",
        "INT_SOLUTION": "DETAILLIERTER LÖSUNGSVORSCHLAG", 
        "INT_ETAPE_1": "Schritt 1: Problemanalyse (10 min)",
        "INT_ETAPE_2": "Schritt 2: Mobilisierung des Wissens (15 min)", 
        "INT_ETAPE_3": "Schritt 3: Gruppenlösung (15 min)",
        "INT_ETAPE_4": "Schritt 4: Synthese und Korrektur (10 min)", 
        "EVAL_PARTIE_1": "TEIL I: BEWERTUNG DER RESSOURCEN",
        "EVAL_SAVOIRS": "A. WISSEN", 
        "EVAL_SAVOIR_FAIRE": "B. KNOW-HOW", 
        "EVAL_PARTIE_2": "TEIL II: BEWERTUNG DER KOMPETENZ",
        "EVAL_SITUATION_PROBLEME": "Problemsituation", 
        "EVAL_PRESENTATION": "PRÄSENTATION",
        "EVAL_QCM_TITRE": "ABSCHNITT A: MULTIPLE-CHOICE-FRAGEN", 
        "EVAL_STRUCTURED_TITRE": "ABSCHNITT B: STRUKTURIERTE FRAGEN",
        "EVAL_PDF_TITLE": "Sequentielle Prüfung",
        "EVAL_PDF_AUTHOR": "TCHATCHI AI - Prüfung",
        "EVAL_CORRIGE_TITRE": "AUSFÜHRLICHER LÖSUNGSSCHLÜSSEL",
        "INT_PDF_TITLE": "Integrationsaktivität",
        "INT_PDF_AUTHOR": "TCHATCHI AI - Pädagogische Aktivität"
    },
    'es': {
        "FICHE_DE_LECON": "FICHA DE LECCIÓN (APC)", 
        "OBJECTIFS": "OBJETIVOS DE APRENDIZAJE", 
        "SITUATION_PROBLEME": "SITUACIÓN PROBLEMA",
        "DEROULEMENT": "DESARROLLO DE LA LECCIÓN", 
        "INTRODUCTION": "Introducción (5 min)", 
        "ACTIVITE_1": "Actividad 1: Descubrimiento (10 min)",
        "ACTIVITE_2": "Actividad 2: Conceptualización y REGISTRO ESCRITO (20 min)", 
        "TRACE_ECRITE": "Registro Escrito",
        "ACTIVITE_3": "Actividad 3: Aplicación (10 min)", 
        "DEVOIRS": "TAREAS", 
        "JEU_BILINGUE": "JUEGO BILINGÜE",
        "HEADER_MATIERE": "Asignatura", 
        "HEADER_CLASSE": "Clase", 
        "HEADER_DUREE": "Duración", 
        "HEADER_LECON": "Lección del Día",
        "PDF_TITLE": "Ficha de Lección", 
        "PDF_AUTHOR": "Asistente Pedagógico TCHATCHI AI",
        "INT_TITRE_PRINCIPAL": "ACTIVIDAD DE INTEGRACIÓN", 
        "INT_COMPETENCES": "Competencias Específicas",
        "INT_SITUATION": "SITUACIÓN DE INTEGRACIÓN (EL PROBLEMA)", 
        "INT_GUIDE": "GUÍA DE RESOLUCIÓN PARA EL DOCENTE",
        "INT_SOLUTION": "PROPUESTA DE SOLUCIÓN DETALLADA", 
        "INT_ETAPE_1": "Paso 1: Análisis del problema (10 min)",
        "INT_ETAPE_2": "Paso 2: Movilización de conocimientos (15 min)", 
        "INT_ETAPE_3": "Paso 3: Resolución en grupo (15 min)",
        "INT_ETAPE_4": "Paso 4: Síntesis y Corrección (10 min)", 
        "EVAL_PARTIE_1": "PARTE I: EVALUACIÓN DE RECURSOS",
        "EVAL_SAVOIRS": "A. SABERES", 
        "EVAL_SAVOIR_FAIRE": "B. SABER HACER", 
        "EVAL_PARTIE_2": "PARTE II: EVALUACIÓN DE LA COMPETENCIA",
        "EVAL_SITUATION_PROBLEME": "Situación Problema", 
        "EVAL_PRESENTATION": "PRESENTACIÓN",
        "EVAL_QCM_TITRE": "SECCIÓN A: PREGUNTAS DE OPCIÓN MÚLTIPLE", 
        "EVAL_STRUCTURED_TITRE": "SECCIÓN B: PREGUNTAS ESTRUCTURADAS",
        "EVAL_PDF_TITLE": "Evaluación Secuencial",
        "EVAL_PDF_AUTHOR": "TCHATCHI AI - Evaluación",
        "EVAL_CORRIGE_TITRE": "CLAVE DE RESPUESTAS DETALLADA",
        "INT_PDF_TITLE": "Actividad de Integración",
        "INT_PDF_AUTHOR": "TCHATCHI AI - Actividad Pedagógica"

    },
    'zh': {
        "FICHE_DE_LECON": "CBA 课程计划", 
        "OBJECTIFS": "学习目标", 
        "SITUATION_PROBLEME": "问题情境", 
        "DEROULEMENT": "课程计划",
        "INTRODUCTION": "介绍 (5 分钟)", 
        "ACTIVITE_1": "活动1：发现 (10 分钟)", 
        "ACTIVITE_2": "活动2：概念化和书面记录 (20 分钟)",
        "TRACE_ECRITE": "书面记录", 
        "ACTIVITE_3": "活动3：应用 (10 分钟)", 
        "DEVOIRS": "家庭作业", 
        "JEU_BILINGUE": "双语游戏",
        "HEADER_MATIERE": "科目", 
        "HEADER_CLASSE": "班级", 
        "HEADER_DUREE": "时长", 
        "HEADER_LECON": "今日课程",
        "PDF_TITLE": "课程计划", 
        "PDF_AUTHOR": "TCHATCHI AI 教学助理", 
        "INT_TITRE_PRINCIPAL": "整合活动", 
        "INT_COMPETENCES": "目标技能",
        "INT_SITUATION": "整合情境（问题）", 
        "INT_GUIDE": "教师解决方案指南", 
        "INT_SOLUTION": "详细建议解决方案",
        "INT_ETAPE_1": "步骤1：问题分析 (10 分钟)", 
        "INT_ETAPE_2": "步骤2：知识动员 (15 分钟)",
        "INT_ETAPE_3": "步骤3：小组解决 (15 分钟)", 
        "INT_ETAPE_4": "步骤4：总结与修正 (10 分钟)",
        "EVAL_PARTIE_1": "第一部分：资源评估", 
        "EVAL_SAVOIRS": "A. 知识", 
        "EVAL_SAVOIR_FAIRE": "B. 技能",
        "EVAL_PARTIE_2": "第二部分：能力评估", 
        "EVAL_SITUATION_PROBLEME": "问题情境", 
        "EVAL_PRESENTATION": "展示",
        "EVAL_QCM_TITRE": "A部分：选择题", 
        "EVAL_STRUCTURED_TITRE": "B部分：结构化问题",
        "EVAL_PDF_TITLE": "顺序评估",
        "EVAL_PDF_AUTHOR": "TCHATCHI AI - 评估",
        "EVAL_CORRIGE_TITRE": "详细答案",
        "INT_PDF_TITLE": "整合活动",
        "INT_PDF_AUTHOR": "TCHATCHI AI - 教学活动"
    },
    'ar': {
        "FICHE_DE_LECON": "خطة درس", "OBJECTIFS": "الأهداف التعليمية", "SITUATION_PROBLEME": "الوضعية المشكلة",
        "DEROULEMENT": "خطة الدرس", "INTRODUCTION": "مقدمة (5 دقائق)", "ACTIVITE_1": "نشاط 1: اكتشاف (10 دقائق)",
        "ACTIVITE_2": "نشاط 2: وضع المفاهيم والسجل المكتوب (20 دقيقة)", "TRACE_ECRITE": "السجل المكتوب",
        "ACTIVITE_3": "نشاط 3: تطبيق (10 دقائق)", "DEVOIRS": "واجب منزلي", "JEU_BILINGUE": "لعبة ثنائية اللغة",
        "HEADER_MATIERE": "المادة", "HEADER_CLASSE": "الفصل", "HEADER_DUREE": "المدة", "HEADER_LECON": "درس اليوم",
        "PDF_TITLE": "خطة الدرس", "PDF_AUTHOR": "مساعد التدريس TCHATCHI AI", "INT_TITRE_PRINCIPAL": "نشاط إدماجي",
        "INT_COMPETENCES": "الكفاءات المستهدفة", "INT_SITUATION": "وضعية الإدماج (المشكلة)", "INT_GUIDE": "دليل الحل للمعلم",
        "INT_SOLUTION": "الحل المقترح المفصل", "INT_ETAPE_1": "الخطوة 1: تحليل المشكلة (10 دقائق)",
        "INT_ETAPE_2": "الخطوة 2: تعبئة المكتسبات (15 دقيقة)", "INT_ETAPE_3": "الخطوة 3: الحل الجماعي (15 دقيقة)",
        "INT_ETAPE_4": "الخطوة 4: التلخيص والتصحيح (10 دقائق)", "EVAL_PARTIE_1": "الجزء الأول: تقييم الموارد",
        "EVAL_SAVOIRS": "أ. المعارف", "EVAL_SAVOIR_FAIRE": "ب. المهارات", "EVAL_PARTIE_2": "الجزء الثاني: تقييم الكفاءة",
        "EVAL_SITUATION_PROBLEME": "وضعية المشكلة", "EVAL_PRESENTATION": "العرض",
        "EVAL_QCM_TITRE": "القسم أ: أسئلة الاختيار من متعدد", "EVAL_STRUCTURED_TITRE": "القسم ب: الأسئلة المنظمة",
         "EVAL_PDF_TITLE": "تقييم تتابعي",
        "EVAL_PDF_AUTHOR": "TCHATCHI AI - تقييم",
        "EVAL_CORRIGE_TITRE": "مفتاح الإجابة المفصل",
        "INT_PDF_TITLE": "نشاط إدماجي",
        "INT_PDF_AUTHOR": "TCHATCHI AI - نشاط تربوي"
    },
    'it': {
        "FICHE_DE_LECON": "PIANO DI LEZIONE (APC)", "OBJECTIFS": "OBIETTIVI DI APPRENDIMENTO", "SITUATION_PROBLEME": "SITUAZIONE PROBLEMATICA",
        "DEROULEMENT": "SVOLGIMENTO DELLA LEZIONE", "INTRODUCTION": "Introduzione (5 min)", "ACTIVITE_1": "Attività 1: Scoperta (10 min)",
        "ACTIVITE_2": "Attività 2: Concettualizzazione e TRACCIA SCRITTA (20 min)", "TRACE_ECRITE": "Traccia Scritta",
        "ACTIVITE_3": "Attività 3: Applicazione (10 min)", "DEVOIRS": "COMPITI PER CASA", "JEU_BILINGUE": "GIOCO BILINGUE",
        "HEADER_MATIERE": "Materia", "HEADER_CLASSE": "Classe", "HEADER_DUREE": "Durata", "HEADER_LECON": "Lezione del Giorno",
        "PDF_TITLE": "Piano di Lezione", "PDF_AUTHOR": "Assistente Pedagogico TCHATCHI AI",
        "INT_TITRE_PRINCIPAL": "ATTIVITÀ DI INTEGRAZIONE", "INT_COMPETENCES": "Competenze Mirate",
        "INT_SITUATION": "SITUAZIONE DI INTEGRAZIONE (IL PROBLEMA)", "INT_GUIDE": "GUIDA ALLA RISOLUZIONE PER L'INSEGNANTE",
        "INT_SOLUTION": "PROPOSTA DI SOLUZIONE DETTAGLIATA", "INT_ETAPE_1": "Passo 1: Analisi del problema (10 min)",
        "INT_ETAPE_2": "Passo 2: Mobilitazione delle conoscenze (15 min)", "INT_ETAPE_3": "Passo 3: Risoluzione in gruppo (15 min)",
        "INT_ETAPE_4": "Passo 4: Sintesi e Correzione (10 min)", "EVAL_PARTIE_1": "PARTE I: VALUTAZIONE DELLE RISORSE",
        "EVAL_SAVOIRS": "A. CONOSCENZE", "EVAL_SAVOIR_FAIRE": "B. ABILITÀ", "EVAL_PARTIE_2": "PARTE II: VALUTAZIONE DELLA COMPETENZA",
        "EVAL_SITUATION_PROBLEME": "Situazione Problematica", "EVAL_PRESENTATION": "PRESENTAZIONE",
        "EVAL_QCM_TITRE": "SEZIONE A: DOMANDE A SCELTA MULTIPLA", "EVAL_STRUCTURED_TITRE": "SEZIONE B: DOMANDE STRUTTURATE",
         "EVAL_PDF_TITLE": "Valutazione Sequenziale",
        "EVAL_PDF_AUTHOR": "TCHATCHI AI - Valutazione",
        "EVAL_CORRIGE_TITRE": "CHIAVE DI RISPOSTA DETTAGLIATA",
        "INT_PDF_TITLE": "Attività di Integrazione",
        "INT_PDF_AUTHOR": "TCHATCHI AI - Attività Pedagogica"
    }
}