import os
from dotenv import load_dotenv

# Charge les variables d'environnement à partir du fichier .env
load_dotenv()

# Récupère la clé API depuis l'environnement
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY") # AJOUT DE LA CLÉ GEMINI
# Nouvelles variables pour l'authentification
GOOGLE_CLIENT_ID = os.getenv("GOOGLE_CLIENT_ID")
GOOGLE_CLIENT_SECRET = os.getenv("GOOGLE_CLIENT_SECRET")
APP_SECRET_KEY = os.getenv("APP_SECRET_KEY")



# On déplace le gros dictionnaire de traductions ici
# =======================================================================
# SECTION 2.5 : DICTIONNAIRE DE TRADUCTIONS (VERSION FINALE COMPLÈTE)
# =======================================================================
TITLES = {
    'fr': {
        "FICHE_DE_LECON": "FICHE DE LEÇON APC", 
        "OBJECTIFS": "OBJECTIFS PÉDAGOGIQUES",
        "SITUATION_PROBLEME": "SITUATION PROBLÈME", 
        "DEROULEMENT": "DÉROULEMENT DE LA LEÇON",
        "INTRODUCTION": "Introduction (5 min)", 
        "ACTIVITE_1": "Activité 1: Découverte (10 min)",
        "ACTIVITE_2": "Activité 2: Conceptualisation et TRACE ÉCRITE (20 min)",
        "TRACE_ECRITE": "Trace Écrite", 
        "ACTIVITE_3": "Activité 3: Application (10 min)",
        "DEVOIRS": "DEVOIRS", 
        "JEU_BILINGUE": "JEU BILINGUE / BILINGUAL GAME",
        "HEADER_MATIERE": "Matière", 
        "HEADER_CLASSE": "Classe", 
        "HEADER_DUREE": "Durée",
        "HEADER_LECON": "Leçon du jour", 
        "PDF_TITLE": "Fiche de Leçon", 
        "PDF_AUTHOR": "Assistant Pédagogique TCHATCHI AI",
        "INT_TITRE_PRINCIPAL": "ACTIVITÉ D'INTÉGRATION", 
        "INT_PALIER_COMPETENCE": "Palier de Compétence visé", # CLÉ CORRIGÉE
        "INT_RESSOURCES_MOBILISER": "Ressources à mobiliser", # NOUVELLE CLÉ
        "INT_CONTROLE_PREREQUIS": "Contrôle des pré-requis", # NOUVELLE CLÉ
        "INT_SITUATION": "SITUATION D'INTÉGRATION (LE PROBLÈME)", 
        "INT_GUIDE": "GUIDE DE RÉSOLUTION POUR L'ENSEIGNANT",
        "INT_SOLUTION": "PROPOSITION DE SOLUTION DÉTAILLÉE",
        "EVAL_PARTIE_1": "PARTIE I : ÉVALUATION DES RESSOURCES", 
        "EVAL_SAVOIRS": "A. SAVOIRS",
        "EVAL_SAVOIR_FAIRE": "B. SAVOIR-FAIRE", 
        "EVAL_PARTIE_2": "PARTIE II : ÉVALUATION DE LA COMPÉTENCE",
        "EVAL_SITUATION_PROBLEME": "Situation Problème", 
        "EVAL_PRESENTATION": "PRÉSENTATION",
        "EVAL_QCM_TITRE": "SECTION A : QUESTIONS À CHOIX MULTIPLES", 
        "EVAL_STRUCTURED_TITRE": "SECTION B : QUESTIONS STRUCTURÉES",
        "EVAL_PDF_TITLE": "Évaluation Séquentielle",
        "EVAL_PDF_AUTHOR": "TCHATCHI AI - Évaluation",
        "EVAL_CORRIGE_TITRE": "CORRIGÉ DÉTAILLÉ",
        "INT_PDF_TITLE": "Activité d'Intégration",
        "INT_PDF_AUTHOR": "TCHATCHI AI - Activité Pédagogique",
         # --- **NOUVELLES CLÉS AJOUTÉES** ---
        "PLAN_LECON": "PLAN DE LA LEÇON",
        "PREREQUIS": "RAPPEL DES PRÉ-REQUIS",
        "APPLICATION_VIE_REELLE": "APPLICATION DANS LA VIE RÉELLE",
        "CONCEPTS_CLES": "PRÉSENTATION DES CONCEPTS",
        "EXERCICES_APPLICATION": "EXERCICES D'APPLICATION",
        "RESSOURCES_NUMERIQUES": "RESSOURCES NUMÉRIQUES COMPLÉMENTAIRES"
    },
    'en': {
        "FICHE_DE_LECON": "CBA LESSON PLAN", 
        "OBJECTIFS": "LEARNING OBJECTIVES",
        "SITUATION_PROBLEME": "PROBLEM SITUATION", 
        "DEROULEMENT": "LESSON PLAN",
        "INTRODUCTION": "Introduction (5 min)", 
        "ACTIVITE_1": "Activity 1: Discovery (10 min)",
        "ACTIVITE_2": "Activity 2: Conceptualization and WRITTEN RECORD (20 min)",
        "TRACE_ECRITE": "Written Record", 
        "ACTIVITE_3": "Activity 3: Application (10 min)",
        "DEVOIRS": "HOMEWORK", 
        "JEU_BILINGUE": "BILINGUAL GAME / JEU BILINGUE",
        "HEADER_MATIERE": "Subject", 
        "HEADER_CLASSE": "Class", 
        "HEADER_DUREE": "Duration",
        "HEADER_LECON": "Lesson of the Day", 
        "PDF_TITLE": "Lesson Plan", 
        "PDF_AUTHOR": "TCHATCHI AI Pedagogical Assistant",
        "INT_TITRE_PRINCIPAL": "INTEGRATION ACTIVITY", 
        "INT_PALIER_COMPETENCE": "Targeted Competency Level", # CORRECTED KEY
        "INT_RESSOURCES_MOBILISER": "Resources to Mobilize", # NEW KEY
        "INT_CONTROLE_PREREQUIS": "Prerequisite Check", # NEW KEY
        "INT_SITUATION": "INTEGRATION SITUATION (THE PROBLEM)", 
        "INT_GUIDE": "RESOLUTION GUIDE FOR THE TEACHER",
        "INT_SOLUTION": "DETAILED PROPOSED SOLUTION",
        "EVAL_PARTIE_1": "PART I: ASSESSMENT OF RESOURCES", 
        "EVAL_SAVOIRS": "A. KNOWLEDGE",
        "EVAL_SAVOIR_FAIRE": "B. KNOW-HOW", 
        "EVAL_PARTIE_2": "PART II: ASSESSMENT OF COMPETENCE",
        "EVAL_SITUATION_PROBLEME": "Problem Situation", 
        "EVAL_PRESENTATION": "PRESENTATION",
        "EVAL_QCM_TITRE": "SECTION A: MULTIPLE CHOICE QUESTIONS", 
        "EVAL_STRUCTURED_TITRE": "SECTION B: STRUCTURED QUESTIONS",
        "EVAL_PDF_TITLE": "Sequential Assessment",
        "EVAL_PDF_AUTHOR": "TCHATCHI AI - Assessment",
        "EVAL_CORRIGE_TITRE": "DETAILED ANSWER KEY",
        "INT_PDF_TITLE": "Integration Activity",
        "INT_PDF_AUTHOR": "TCHATCHI AI - Pedagogical Activity",

        # --- **NOUVELLES CLÉS AJOUTÉES** ---
        "PLAN_LECON": "LESSON PLAN",
        "PREREQUIS": "PREVIOUS KNOWLEDGE REVIEW",
        "APPLICATION_VIE_REELLE": "REAL LIFE APPLICATION",
        "CONCEPTS_CLES": "PRESENTATION OF CONCEPTS",
        "EXERCICES_APPLICATION": "APPLICATION EXERCISES",
        "RESSOURCES_NUMERIQUES": "ADDITIONAL DIGITAL RESOURCES"
    },
    'de': {
        "FICHE_DE_LECON": "LEKTIONSPLAN (CBA)", 
        "OBJECTIFS": "LERNZIELE", 
        "SITUATION_PROBLEME": "PROBLEMSITUATION",
        "DEROULEMENT": "LEKTIONSVERLAUF", 
        "INTRODUCTION": "Einführung (5 min)", 
        "ACTIVITE_1": "Aktivität 1: Entdeckung (10 min)",
        "ACTIVITE_2": "Aktivität 2: Konzeptualisierung und SCHRIFTLICHER EINTRAG (20 min)", 
        "TRACE_ECRITE": "Schriftlicher Eintrag",
        "ACTIVITE_3": "Aktivität 3: Anwendung (10 min)", 
        "DEVOIRS": "HAUSAUFGABEN", 
        "JEU_BILINGUE": "ZWEISPRACHIGES SPIEL",
        "HEADER_MATIERE": "Fach", 
        "HEADER_CLASSE": "Klasse", 
        "HEADER_DUREE": "Dauer", 
        "HEADER_LECON": "Heutige Lektion",
        "PDF_TITLE": "Lektionsplan", 
        "PDF_AUTHOR": "Pädagogischer Assistent TCHATCHI AI",
        "INT_TITRE_PRINCIPAL": "INTEGRATIONSAKTIVITÄT",
        "INT_PALIER_COMPETENCE": "Angestrebte Kompetenzstufe",
        "INT_RESSOURCES_MOBILISER": "Zu mobilisierende Ressourcen",
        "INT_CONTROLE_PREREQUIS": "Überprüfung der Vorkenntnisse",
        "INT_SITUATION": "INTEGRATIONSSITUATION (DAS PROBLEM)", 
        "INT_GUIDE": "LÖSUNGSLEITFADEN FÜR DEN LEHRER",
        "INT_SOLUTION": "DETAILLIERTER LÖSUNGSVORSCHLAG",
        "EVAL_PARTIE_1": "TEIL I: BEWERTUNG DER RESSOURCEN",
        "EVAL_SAVOIRS": "A. WISSEN", 
        "EVAL_SAVOIR_FAIRE": "B. KNOW-HOW", 
        "EVAL_PARTIE_2": "TEIL II: BEWERTUNG DER KOMPETENZ",
        "EVAL_SITUATION_PROBLEME": "Problemsituation", 
        "EVAL_PRESENTATION": "PRÄSENTATION",
        "EVAL_QCM_TITRE": "ABSCHNITT A: MULTIPLE-CHOICE-FRAGEN", 
        "EVAL_STRUCTURED_TITRE": "ABSCHNITT B: STRUKTURIERTE FRAGEN",
        "EVAL_PDF_TITLE": "Sequentielle Prüfung",
        "EVAL_PDF_AUTHOR": "TCHATCHI AI - Prüfung",
        "EVAL_CORRIGE_TITRE": "AUSFÜHRLICHER LÖSUNGSSCHLÜSSEL",
        "INT_PDF_TITLE": "Integrationsaktivität",
        "INT_PDF_AUTHOR": "TCHATCHI AI - Pädagogische Aktivität",
         # --- NOUVELLES CLÉS AJOUTÉES ---
        "PLAN_LECON": "LEKTIONSPLAN",
        "PREREQUIS": "WIEDERHOLUNG DER VORKENNTNISSE",
        "APPLICATION_VIE_REELLE": "ANWENDUNG IM WIRKLICHEN LEBEN",
        "CONCEPTS_CLES": "PRÄSENTATION DER KONZEPTE",
        "EXERCICES_APPLICATION": "ANWENDUNGSÜBUNGEN",
        "RESSOURCES_NUMERIQUES": "ZUSÄTZLICHE DIGITALE RESSOURCEN"
    },
    'es': {
        "FICHE_DE_LECON": "FICHA DE LECCIÓN (APC)", 
        "OBJECTIFS": "OBJETIVOS DE APRENDIZAJE", 
        "SITUATION_PROBLEME": "SITUACIÓN PROBLEMA",
        "DEROULEMENT": "DESARROLLO DE LA LECCIÓN", 
        "INTRODUCTION": "Introducción (5 min)", 
        "ACTIVITE_1": "Actividad 1: Descubrimiento (10 min)",
        "ACTIVITE_2": "Actividad 2: Conceptualización y REGISTRO ESCRITO (20 min)", 
        "TRACE_ECRITE": "Registro Escrito",
        "ACTIVITE_3": "Actividad 3: Aplicación (10 min)", 
        "DEVOIRS": "TAREAS", 
        "JEU_BILINGUE": "JUEGO BILINGÜE",
        "HEADER_MATIERE": "Asignatura", 
        "HEADER_CLASSE": "Clase", 
        "HEADER_DUREE": "Duración", 
        "HEADER_LECON": "Lección del Día",
        "PDF_TITLE": "Ficha de Lección", 
        "PDF_AUTHOR": "Asistente Pedagógico TCHATCHI AI",
        "INT_TITRE_PRINCIPAL": "ACTIVIDAD DE INTEGRACIÓN", 
        "INT_COMPETENCES": "Competencias Específicas",
        "INT_SITUATION": "SITUACIÓN DE INTEGRACIÓN (EL PROBLEMA)", 
        "INT_GUIDE": "GUÍA DE RESOLUCIÓN PARA EL DOCENTE",
        "INT_SOLUTION": "PROPUESTA DE SOLUCIÓN DETALLADA", 
        "INT_TITRE_PRINCIPAL": "ACTIVIDAD DE INTEGRACIÓN",
        "INT_PALIER_COMPETENCE": "Nivel de Competencia Específico",
        "INT_RESSOURCES_MOBILISER": "Recursos a movilizar",
        "INT_CONTROLE_PREREQUIS": "Control de Prerrequisitos",
        "INT_SITUATION": "SITUACIÓN DE INTEGRACIÓN (EL PROBLEMA)", 
        "INT_GUIDE": "GUÍA DE RESOLUCIÓN PARA EL DOCENTE",
        "INT_SOLUTION": "PROPUESTA DE SOLUCIÓN DETALLADA",
        "EVAL_PARTIE_1": "PARTE I: EVALUACIÓN DE RECURSOS",
        "EVAL_SAVOIRS": "A. SABERES", 
        "EVAL_SAVOIR_FAIRE": "B. SABER HACER", 
        "EVAL_PARTIE_2": "PARTE II: EVALUACIÓN DE LA COMPETENCIA",
        "EVAL_SITUATION_PROBLEME": "Situación Problema", 
        "EVAL_PRESENTATION": "PRESENTACIÓN",
        "EVAL_QCM_TITRE": "SECCIÓN A: PREGUNTAS DE OPCIÓN MÚLTIPLE", 
        "EVAL_STRUCTURED_TITRE": "SECCIÓN B: PREGUNTAS ESTRUCTURADAS",
        "EVAL_PDF_TITLE": "Evaluación Secuencial",
        "EVAL_PDF_AUTHOR": "TCHATCHI AI - Evaluación",
        "EVAL_CORRIGE_TITRE": "CLAVE DE RESPUESTAS DETALLADA",
        "INT_PDF_TITLE": "Actividad de Integración",
        "INT_PDF_AUTHOR": "TCHATCHI AI - Actividad Pedagógica",
        # --- NOUVELLES CLÉS AJOUTÉES ---
        "PLAN_LECON": "PLAN DE LA LECCIÓN",
        "PREREQUIS": "REPASO DE CONOCIMIENTOS PREVIOS",
        "APPLICATION_VIE_REELLE": "APLICACIÓN EN LA VIDA REAL",
        "CONCEPTS_CLES": "PRESENTACIÓN DE CONCEPTOS",
        "EXERCICES_APPLICATION": "EJERCICIOS DE APLICACIÓN",
        "RESSOURCES_NUMERIQUES": "RECURSOS DIGITALES ADICIONALES"

    },
    'zh': {
        "FICHE_DE_LECON": "CBA 课程计划", 
        "OBJECTIFS": "学习目标", 
        "SITUATION_PROBLEME": "问题情境", 
        "DEROULEMENT": "课程计划",
        "INTRODUCTION": "介绍 (5 分钟)", 
        "ACTIVITE_1": "活动1：发现 (10 分钟)", 
        "ACTIVITE_2": "活动2：概念化和书面记录 (20 分钟)",
        "TRACE_ECRITE": "书面记录", 
        "ACTIVITE_3": "活动3：应用 (10 分钟)", 
        "DEVOIRS": "家庭作业", 
        "JEU_BILINGUE": "双语游戏",
        "HEADER_MATIERE": "科目", 
        "HEADER_CLASSE": "班级", 
        "HEADER_DUREE": "时长", 
        "HEADER_LECON": "今日课程",
        "PDF_TITLE": "课程计划", 
        "PDF_AUTHOR": "TCHATCHI AI 教学助理", 
        "INT_TITRE_PRINCIPAL": "整合活动", 
        "INT_COMPETENCES": "目标技能",
        "INT_SITUATION": "整合情境（问题）", 
        "INT_GUIDE": "教师解决方案指南", 
        "INT_SOLUTION": "详细建议解决方案",
         "INT_TITRE_PRINCIPAL": "整合活动",
        "INT_PALIER_COMPETENCE": "目标能力水平",
        "INT_RESSOURCES_MOBILISER": "需调动资源",
        "INT_CONTROLE_PREREQUIS": "先决条件检查",
        "INT_SITUATION": "整合情境（问题）", 
        "INT_GUIDE": "教师解决方案指南", 
        "INT_SOLUTION": "详细建议解决方案",
        "EVAL_PARTIE_1": "第一部分：资源评估", 
        "EVAL_SAVOIRS": "A. 知识", 
        "EVAL_SAVOIR_FAIRE": "B. 技能",
        "EVAL_PARTIE_2": "第二部分：能力评估", 
        "EVAL_SITUATION_PROBLEME": "问题情境", 
        "EVAL_PRESENTATION": "展示",
        "EVAL_QCM_TITRE": "A部分：选择题", 
        "EVAL_STRUCTURED_TITRE": "B部分：结构化问题",
        "EVAL_PDF_TITLE": "顺序评估",
        "EVAL_PDF_AUTHOR": "TCHATCHI AI - 评估",
        "EVAL_CORRIGE_TITRE": "详细答案",
        "INT_PDF_TITLE": "整合活动",
        "INT_PDF_AUTHOR": "TCHATCHI AI - 教学活动",
        # --- NOUVELLES CLÉS AJOUTÉES ---
        "PLAN_LECON": "课程计划",
        "PREREQUIS": "前提知识回顾",
        "APPLICATION_VIE_REELLE": "实际生活应用",
        "CONCEPTS_CLES": "概念介绍",
        "EXERCICES_APPLICATION": "应用练习",
        "RESSOURCES_NUMERIQUES": "额外的数字资源"
    },
    'ar': {
        "FICHE_DE_LECON": "خطة درس", "OBJECTIFS": "الأهداف التعليمية", "SITUATION_PROBLEME": "الوضعية المشكلة",
        "DEROULEMENT": "خطة الدرس", "INTRODUCTION": "مقدمة (5 دقائق)", "ACTIVITE_1": "نشاط 1: اكتشاف (10 دقائق)",
        "ACTIVITE_2": "نشاط 2: وضع المفاهيم والسجل المكتوب (20 دقيقة)", "TRACE_ECRITE": "السجل المكتوب",
        "ACTIVITE_3": "نشاط 3: تطبيق (10 دقائق)", "DEVOIRS": "واجب منزلي", "JEU_BILINGUE": "لعبة ثنائية اللغة",
        "HEADER_MATIERE": "المادة", "HEADER_CLASSE": "الفصل", "HEADER_DUREE": "المدة", "HEADER_LECON": "درس اليوم",
        "PDF_TITLE": "خطة الدرس", "PDF_AUTHOR": "مساعد التدريس TCHATCHI AI", "INT_TITRE_PRINCIPAL": "نشاط إدماجي",
        "INT_TITRE_PRINCIPAL": "نشاط إدماجي",
        "INT_PALIER_COMPETENCE": "مستوى الكفاءة المستهدف",
        "INT_RESSOURCES_MOBILISER": "الموارد المطلوب تعبئتها",
        "INT_CONTROLE_PREREQUIS": "التحقق من المتطلبات المسبقة",
        "INT_SITUATION": "وضعية الإدماج (المشكلة)", 
        "INT_GUIDE": "دليل الحل للمعلم",
        "INT_SOLUTION": "الحل المقترح المفصل",
        "EVAL_SAVOIRS": "أ. المعارف", "EVAL_SAVOIR_FAIRE": "ب. المهارات", "EVAL_PARTIE_2": "الجزء الثاني: تقييم الكفاءة",
        "EVAL_SITUATION_PROBLEME": "وضعية المشكلة", "EVAL_PRESENTATION": "العرض",
        "EVAL_QCM_TITRE": "القسم أ: أسئلة الاختيار من متعدد", "EVAL_STRUCTURED_TITRE": "القسم ب: الأسئلة المنظمة",
         "EVAL_PDF_TITLE": "تقييم تتابعي",
        "EVAL_PDF_AUTHOR": "TCHATCHI AI - تقييم",
        "EVAL_CORRIGE_TITRE": "مفتاح الإجابة المفصل",
        "INT_PDF_TITLE": "نشاط إدماجي",
        "INT_PDF_AUTHOR": "TCHATCHI AI - نشاط تربوي",
        # --- NOUVELLES CLÉS AJOUTÉES ---
        "PLAN_LECON": "خطة الدرس",
        "PREREQUIS": "مراجعة المعرفة السابقة",
        "APPLICATION_VIE_REELLE": "تطبيق واقعي",
        "CONCEPTS_CLES": "عرض المفاهيم",
        "EXERCICES_APPLICATION": "تمارين تطبيقية",
        "RESSOURCES_NUMERIQUES": "مصادر رقمية إضافية"
    },
    'it': {
        "FICHE_DE_LECON": "PIANO DI LEZIONE (APC)", "OBJECTIFS": "OBIETTIVI DI APPRENDIMENTO", "SITUATION_PROBLEME": "SITUAZIONE PROBLEMATICA",
        "DEROULEMENT": "SVOLGIMENTO DELLA LEZIONE", "INTRODUCTION": "Introduzione (5 min)", "ACTIVITE_1": "Attività 1: Scoperta (10 min)",
        "ACTIVITE_2": "Attività 2: Concettualizzazione e TRACCIA SCRITTA (20 min)", "TRACE_ECRITE": "Traccia Scritta",
        "ACTIVITE_3": "Attività 3: Applicazione (10 min)", "DEVOIRS": "COMPITI PER CASA", "JEU_BILINGUE": "GIOCO BILINGUE",
        "HEADER_MATIERE": "Materia", "HEADER_CLASSE": "Classe", "HEADER_DUREE": "Durata", "HEADER_LECON": "Lezione del Giorno",
        "PDF_TITLE": "Piano di Lezione", "PDF_AUTHOR": "Assistente Pedagogico TCHATCHI AI",
        "INT_TITRE_PRINCIPAL": "ATTIVITÀ DI INTEGRAZIONE",
        "INT_PALIER_COMPETENCE": "Livello di Competenza Mirato",
        "INT_RESSOURCES_MOBILISER": "Risorse da Mobilitare",
        "INT_CONTROLE_PREREQUIS": "Verifica dei Prerequisiti",
        "INT_SITUATION": "SITUAZIONE DI INTEGRAZIONE (IL PROBLEMA)", 
        "INT_GUIDE": "GUIDA ALLA RISOLUZIONE PER L'INSEGNANTE",
        "INT_SOLUTION": "PROPOSTA DI SOLUZIONE DETTAGLIATA",
        "EVAL_SAVOIRS": "A. CONOSCENZE", "EVAL_SAVOIR_FAIRE": "B. ABILITÀ", "EVAL_PARTIE_2": "PARTE II: VALUTAZIONE DELLA COMPETENZA",
        "EVAL_SITUATION_PROBLEME": "Situazione Problematica", "EVAL_PRESENTATION": "PRESENTAZIONE",
        "EVAL_QCM_TITRE": "SEZIONE A: DOMANDE A SCELTA MULTIPLA", "EVAL_STRUCTURED_TITRE": "SEZIONE B: DOMANDE STRUTTURATE",
         "EVAL_PDF_TITLE": "Valutazione Sequenziale",
        "EVAL_PDF_AUTHOR": "TCHATCHI AI - Valutazione",
        "EVAL_CORRIGE_TITRE": "CHIAVE DI RISPOSTA DETTAGLIATA",
        "INT_PDF_TITLE": "Attività di Integrazione",
        "INT_PDF_AUTHOR": "TCHATCHI AI - Attività Pedagogica",
         # --- NOUVELLES CLÉS AJOUTÉES ---
        "PLAN_LECON": "PIANO DELLA LEZIONE",
        "PREREQUIS": "REVISIONE DELLE CONOSCENZE PRECEDENTI",
        "APPLICATION_VIE_REELLE": "APPLICAZIONE NELLA VITA REALE",
        "CONCEPTS_CLES": "PRESENTAZIONE DEI CONCETTI",
        "EXERCICES_APPLICATION": "ESERCIZI DI APPLICAZIONE",
        "RESSOURCES_NUMERIQUES": "RISORSE DIGITALI AGGIUNTIVE"
    }
}