services:
  - type: web
    name: tchatchi-ai
    # On dit à Render d'utiliser Docker, pas son environnement Python natif.
    env: docker
    plan: free
    region: frankfurt

    # On garde les variables d'environnement.
    # Elles seront injectées dans notre machine Docker.
    envVars:
      - key: SUPABASE_URL
        fromSecret: true
      - key: SUPABASE_KEY
        fromSecret: true
      - key: OPENAI_API_KEY
        fromSecret: true