services:
  - type: web
    # Toutes les propriétés ci-dessous sont indentées de 2 espaces
    # pour appartenir au service défini par le tiret ci-dessus.
    name: tchatchi-ai
    env: python
    plan: free
    region: frankfurt

    disks:
      - name: data-disk
        mountPath: /var/data/tchatchi-data
        sizeGB: 1

    envVars:
      - key: RENDER_DISK_PATH
        value: /var/data/tchatchi-data
      
      - key: OPENAI_API_KEY
        fromSecret: true
        
      - key: PYTHON_VERSION
        value: 3.11.4

    buildCommand: "./build.sh"

    startCommand: "gunicorn --worker-tmp-dir /dev/shm app:app"